Update gh-pages.yml

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -29,15 +29,20 @@ jobs:
       - name: Build site
         run: hugo --minify
 
-      - name: List files before uploading
-        run: ls -R public/  # Debugging step
+      - name: Check Hugo Build Output
+        run: |
+          if [ -d "public" ]; then 
+            echo "Public directory exists"; 
+            ls -la public; 
+          else 
+            echo "Public directory is missing"; 
+            exit 1; 
+          fi
 
       - name: Upload artifact
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-pages-artifact@v2
         with:
-          name: github-pages
           path: ./public
-          retention-days: 1
 
   deploy:
     runs-on: ubuntu-latest
@@ -46,18 +51,9 @@ jobs:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     steps:
-      - name: List available artifacts
-        run: ls -l ${{ runner.temp }}/_github_workflow/  # Debugging step
-
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: github-pages
-          path: public
-
-      - name: Check Downloaded Files
-        run: ls -l public/  # Debugging step
+      - name: Check Available Artifacts
+        run: ls -la ${{ runner.temp }}/_github_workflow/
 
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v4
+        uses: actions/deploy-pages@v3
